### ISSUE TITLE
Create simple "Box-like" case

### ISSUE THREAD

**Issue by hmgaspar** [shiplab/vesseljs#11]
Simple box-like
3 blocks

To test Ship.JS calculations and in the future solve "Trim/List" problems.

**Comment by MrEranwe** [comment]
I've created blockCase_compare.html (in vesseljs/examples) and blockCase.JSON (in vesseljs\examples\data\ship_specifications). I've calculated some values and I've created a table that compares them. 

TO DO: Add more values (maybe some request) and fill the blanks of the table.

**Comment by EliasHasle** [comment]
I request having a variety of very simple (manually computable) hull shapes, for more thorough debugging of the calculations. For example the case of a flat-bottom ship to test if the submerged area is calculated right.
