### ISSUE TITLE
Update blockCase_compare.html 

### ISSUE THREAD

**Issue by hmgaspar** [shiplab/vesseljs#15]
Modify "Comparison" to Hydrostatics (draft is input)

Add "General Arrangement" with a table of Blocks
    prop1 .  prop2 .  prop3 .  
b1
b2
b3

Sum by hand and by software

Add "Whole Ship" Table, with ALL properties, draft and other calculations are output. Later in the future we will add slides to it.

**Comment by EliasHasle** [comment]
This issue is sort of handled by the examples in category "Hydrostatics and Stability". https://shiplab.github.io/vesseljs/examples/

Closing.
