### ISSUE TITLE
Publishing Vesseljs on npm

### ISSUE THREAD

**Issue by hannydevelop** [shiplab/vesseljs#170]
Overtime, I built a project with vessels by downloading the zip file and pointing my project to vessel js source code. However, this has become ambiguous as deploying this projects online involves the addition of vessels source code.

## Solution
- Create an `npm` package for Vessels
- Add CDN support for Vessels JavaScript

I have experience doing this, if it's okay with the team, I can work on this with my fork and update the readme on installation guide.

**Comment by hmgaspar** [comment]
Hi,

The library is a little "abandoned", as we are not able to prioritize it.
Maybe next semester we are back to update it. As for the NPM, you are
welcome to fix it, but it may be a provisory fix, as I expect changes next
semester.

Henrique

**Comment by hmgaspar** [comment]
Btw, we have a npm running -
https://www.npmjs.com/package/ntnu-vessel?activeTab=dependencies. We use
that for Observable.HQ.

Henrique

**Comment by hmgaspar** [comment]
Closed by now - npm is available.
