### ISSUE TITLE
Twin Outboards

### ISSUE THREAD

**Issue by rellufdarb** [shiplab/vesseljs#180]
I am a Marine Rescue volunteer and we have a twin outboard vessel that does both towing astern and towing alongside. We often use the motors in ahead/astern (ie split controls) to manoeuvre in close quarters. I would like to use vessel.js to train helmsmen and I cant seem to find an example with separate controls for two motors. Is there already a model that I could use for this purpose If not, some hints on how to create the appropriate models would be appreciated

**Comment by hmgaspar** [comment]
Hi, there is not. We are in the process of improving the tutorials of the library, but we do not plan to include the development of twin outboard at this stage.
