### ISSUE TITLE
Calculate intact stability

### ISSUE THREAD

**Issue by icarofonseca** [shiplab/vesseljs#2]
GM = KB + BM - KG

**Comment by EliasHasle** [comment]
@MrEranwe All of the required attributes are (in theory) calculated by the existing methods in vessel and hull.

You will have to do something like this (in a method in Vessel.prototype. vesselState will be a parameter):
var T = this.calculateDraft(vesselState);
var ha = this.structure.hull.calculateAttributesAtDraft(T);
var w = this.getWeight(vesselState);

Then find the values you need for the calculation within these three results.

**Comment by EliasHasle** [comment]
I have created a dev branch. It would be nice if you make changes only to that one initially, so that we can review, test and revide the code before committing to master.

**Comment by hmgaspar** [comment]
GM Solved

**Comment by hmgaspar** [comment]
BM KB is misplaced, change it.

**Comment by hmgaspar** [comment]
Get real VCB/TCB values from Buoyancy calculations

**Comment by EliasHasle** [comment]
Since we have both Ixwp and Iywp, we should be able to calculate longitudinal and transverse GM. :-)

**Comment by EliasHasle** [comment]
@MrEranwe Would you mind checking that I have made the new stability calculation method right? I replaced the placeholder calculations with values from the corrected hull calculations, and added distinction between longitudinal values and transverse values. I use waterplane Ix for BMT and GMT, and waterplane Iy for BML and GML, and set BM to BMT and GM to GMT (returning GMT, GML GMT, BML separately too). Is it OK?

**Comment by hmgaspar** [comment]
Closing - we can always open a new when this is priority again.
