### ISSUE TITLE
Which functions should be exposed, and how?

### ISSUE THREAD

**Issue by EliasHasle** [shiplab/vesseljs#20]
Right now, a few useful functions are exposed through the object Vessel.f. If there are any other functions in the functions folder that you would like to use in your examples, we can expose each of them by making a tiny modification to makeBuild.py before building.

Should the vector operations be in Vessel.v, perhaps? Any other suggestions on how to do this without making a mess?

**Comment by icarofonseca** [comment]
I suggest something like Vessel.vectors or Vessel.math.

**Comment by EliasHasle** [comment]
Yeah, and maybe we can do something like this:
Vessel.Vector.add(v1,v2)

and Vector.add(v1,v2) internally instead of addVec(v1,2)

I kind of like "vec3", which is used in OpenGL for 3D vector declaration
and construction. (I don't think it is very typical Javascript, though.)

2017-11-16 14:46 GMT+01:00 Ícaro Fonseca <notifications@github.com>:

**Comment by EliasHasle** [comment]
I think we can go with Vessel.Vectors.add(v1, v2) etc. Then the users are
at liberty to use whatever shorthands they see fit, such as
vec=Vessel.Vectors.

16. nov. 2017 20.15 skrev "Elias Hasle" <elias.hasle@gmail.com>:

**Comment by EliasHasle** [comment]
#30 addresses vector operations.

Other math operations can be added as needed. I close this for now.
