### ISSUE TITLE
Example with Weight as input

### ISSUE THREAD

**Issue by hmgaspar** [shiplab/vesseljs#21]
Similar example with blocks and weight as input, adding GZ curves.

**Comment by icarofonseca** [comment]
Include button to add blocks, text fields to define block positions. Move app to master and document on wiki when it's done.

**Comment by icarofonseca** [comment]
There is a beta version of the app on https://shiplab.github.io/vesseljs/examples/Ship_stability_with_blocks.html. Give me feedback on whether you like the direction the app is going.

Next features should add:
* Text fields to define x and y positions of blocks. The app should include a warning that the x position is merely for spatial arrangement, as the library does not support trim calculations.
* A button to update calculations and visualizations. Calculations are not responsive enough for the current `onchange` approach.
* Documentation on wiki.

**Comment by EliasHasle** [comment]
I think it is a sensible extension of the table approach. It is one possible way of editing the block configuration. I am working on a more visually oriented approach. I guess there is no reason we can't have both, or at least experiment with both.

Regarding responsivity, I agree that modifying immediately on every single change might not be the best solution. I don't particularly like having to click a button either, though. Maybe we can use a [setInterval ](https://www.w3schools.com/jsref/met_win_setinterval.asp) that calls an update function at most once every second. Each onChange then should set a shared "confModified" flag that is checked by the update function before doing any expensive calculations, and reset to false afterwards.

**Comment by EliasHasle** [comment]
OK, now I looked at the code. Right, it is not a good solution to rebuild the entire visualization on every change. It is the easiest solution, though. I believe a better solution will be to add an interface to the Ship3D prototype, for simultaneously modifying the Ship3D and the underlying Ship.

My initial concern about calculations was with the draft and geometric attributes, and that concern is still alive.

**Comment by icarofonseca** [comment]
I'm working on a new version of the code, I should commit in some minutes. Then you can suggest any improvements based on the new version.

**Comment by icarofonseca** [comment]
But the points you made on your post will remain on the new version, though.
