### ISSUE TITLE
How to use branches properly

### ISSUE THREAD

**Issue by EliasHasle** [shiplab/vesseljs#27]
<details><summary>Outdated</summary>
I don't know if we are doing it right, because it becomes a massive mess every time I am trying to update to master. Maybe, instead of having a common dev branch, we should fork out our own branches for development, and send pull requests on the changes. Then changes to non-essential files can be approved (pulled, merged) by the one who creates the pull request, and changes to essential files can be approved by me after careful review.

Any views on this? I would like to delete the dev branch soon, but maybe we should first check that the current state of the master branch is up to date with your newest versions of the files. Because I am not perfectly certain that I did everything right when merging.</details>

**Comment by icarofonseca** [comment]
Ok, if this should make the version control simpler, it's fine for me. I already verified that all modifications I committed to dev made it to master.

**Comment by EliasHasle** [comment]
I am not sure, really. But I think we can give it a try.

**Comment by EliasHasle** [comment]
Now I have removed the dev branch, and completed a commit and PR with my own fork. It works.

Just do like me:
1. Click "fork" in the upper right on this site (and project, of course) to create your own fork from the master branch.
2. Backup your local changes.
3. In GitHub desktop (if you are using that), clone your new fork to a local repository.
4. Copy in your local changes.
5. Commit changes and sync, in GitHub desktop.
6. Send pull request to master.
7. If you are only making changes to examples, you can merge the PR right away.

Later on, after making local changes, you only have to repeat steps 5,6,7. But I believe that before making new changes, it is good to make sure that your fork is up to date.

**Comment by EliasHasle** [comment]
Note also that forking allows you to test your own version of the GitHub pages. Just go to project settings, and find the GitHub pages section. Here is an example from my fork (master is up to date right now, but I could have another version running here): https://eliashasle.github.io/vesseljs/examples/Ship3D_GA.html

**Comment by EliasHasle** [comment]
Now it looks like one can use "update from shiplab/master" in github desktop, but maybe it is necessary to click "sync" first. Hm.

**Comment by icarofonseca** [comment]
Ok, I'm using a fork now, as you can see with PR #35.

**Comment by icarofonseca** [comment]
By the way, let's make this a contributing guideline and write it somewhere on the repo or wiki.

**Comment by EliasHasle** [comment]
Good idea. Anyway, I think this issue should still be open, as we are
evaluating the procedure, and there is a chance we will do some
modifications or add other procedures/branches too. After all, we (even
you, I believe) are somewhat beginners in git/github.

4. jan. 2018 01.13 skrev "Ícaro Fonseca" <notifications@github.com>:

By the way, let's make this a contributing guideline and write it somewhere
on the repo or wiki.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shiplab/vesseljs/issues/27#issuecomment-355164121>, or mute
the thread

**Comment by EliasHasle** [comment]
Now (again) I recommend following the example of three.js. They have a `master` branch that is updated every second week or so, representing a release (monthly releases may perhaps be more realistic for vessel.js), and a `dev` branch that is updated much more frequently. Only well-discussed and well-tested changes make it to `master`. In practice, this means greater changes are rarely introduced even to `dev` in the last days before a new `master` release, because `dev` must mature enough to be ready for `master`. Pull requests are based on `dev`, and can stay open for weeks and months (sometimes years, but I do not recommend that...), depending on how complex or controversial they are.

**Comment by EliasHasle** [comment]
Ship3D and Ship3D_v2 should be merged together. Likewise with ShipState and ShipState_new. Having them separate is just a mess. However, merging them will also require updating, or removing, a few old examples. One option will be to make a small "Legacy" release to support, and then move faster forward.

**Comment by EliasHasle** [comment]
@hmgaspar I now added a `dev` branch again, and I request that you make it the default branch (I don't think I have the privileges). Then we touch `master` only when we are ready for a new release.

**Comment by hmgaspar** [comment]
Ok, good idea.
