### ISSUE TITLE
Draft and hull specs/attributes

### ISSUE THREAD

**Issue by icarofonseca** [shiplab/vesseljs#3]
Include slide for changing fulfilled tank volume.

**Comment by hmgaspar** [comment]
Double check calculations and push master when done.

**Comment by EliasHasle** [comment]
I took the liberty to push to master even before everything is OK. That is because I have fixed countless bugs, and everything seems to be working at least as well as before.

I have introduced a small debug tool under examples: https://shiplab.github.io/vesseljs/examples/PX121_calculations.html

Ixwp and Iywp are still a long way off. But as far as I can see, all other values look quite reasonable. I will of course continue debugging, and it will be interesting to have @MrEranwe 's work on #11 as another debug tool.

**Comment by MrEranwe** [comment]
Hey Elias,

I'm going to start working on it now. I hope I have something finished
before the end of today.

Regards,

Alejandro

**Comment by EliasHasle** [comment]
Status for calculations run on the block case (#11):
The calculation of wetted area ("As") does not yet account for end caps. But even when adding two times the calculated projected area (which should give an upper bound, at least approximately), the number is still much lower than the manually calculated wetted area. This suggests that there is at least one other error too, either in the calculation of wetted area or in that of projected area.
The calculation of center of bouyancy ("Cv") is broken, and returns (0,0,0).
Waterplane Ix and Iy (Ixwp, Iywp) are off by a couple orders of magnitude.
Cb is way off. I expected exactly 0.5 (not accounting for trim), and it returns 0.99725.
Submerged volume ("Vs") does not align with the assumed displacement. A bug here is probably causing the Cb problem too.

The rest of the calculated values are within the margin expected from the difference in accounting or not accounting for trim.

I will look into the problems, and try to solve them during this week.

**Comment by MrEranwe** [comment]
Hey Elias, don't worry about the values. The weight is not right and it
gives a not valid T and therefore, all the values that depend on it. I'm
working on are wrong it,

Regards,

Alejandro

**Comment by EliasHasle** [comment]
Check out my new comparison file in the dev branch. It compares the same
values, calculated from the same draft (even if it is the wrong draft, and
doesn't account for trim).

None of the "manual" calculations are really hand-made, but they are made
from simple formulas tailored to the triangular prism ship that you
specified.

2017-10-27 8:44 GMT+02:00 Vicente Alejandro Iváñez Encinas <
notifications@github.com>:

**Comment by EliasHasle** [comment]
Now it almost passes the blockCase_compare_json.html test. Only the z
component of the center of submerged volume deviates signfificantly from
the hand-calculated value. It looks like more zero-offset areas are sent
to the patchColumnCalculation function than I would expect. (Potential
bug.)

I have (temporarily) introduced simpler volume and area calculations
during debugging, and will try to reintroduce the bilinear patches, as
they give higher accuracy when they work (at least for the volume, where there is a siple analytical solution to the integral).
