### ISSUE TITLE
Need better hull for the PX121

### ISSUE THREAD

**Issue by EliasHasle** [shiplab/vesseljs#32]
The current hull is from a fishing boat. It does not fit very well.

I believe it is not too hard to just generate a hull shape that encloses the objects and satisfies a few constraints, such as symmetry, smoothness along sides (?), monotonic growth from ends to greatest width.

I just want us to keep it in mind, even though it is not of the highest priority yet.

**Comment by icarofonseca** [comment]
Related to the PX121 specification, but slightly off-topic, why is it that the lightweight of the tanks are the product of the dimensions times 10 (10*length*beam*height)?

**Comment by EliasHasle** [comment]
You are welcome to change this to a function of surface area instead. It is
just placeholder data anyway.

1. feb. 2018 01.36 skrev "Ícaro Fonseca" <notifications@github.com>:

Related to the PX121 specification, but slightly off-topic, why is it that
the lightweight of the tanks are the product of the dimensions times 10 (10
*length*beam*height)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shiplab/vesseljs/issues/32#issuecomment-362118831>, or mute
the thread

**Comment by EliasHasle** [comment]
Will be followed up in #58. Closing here.
