### ISSUE TITLE
Scale and Rotation to Derived Objects

### ISSUE THREAD

**Issue by hmgaspar** [shiplab/vesseljs#57]
Add and object with info for scale and rotation, and make it optional for derivedObjects. These changes must be incorporated in the 3D.

Example "scale_rotation" = {0.5, 3, 1.7, 90, 0, 270}

**Comment by icarofonseca** [comment]
I used some code from my thesis to create a simple [ship scaling app](https://shiplab.github.io/vesseljs/examples/scaleApp.html), maybe it is useful for this task.

Maybe in the future this app can be expanded with multiple options to edit ship specifications using GUIs instead of forcing the user to edit JSONs directly.

**Comment by EliasHasle** [comment]
Thinking about this, rotation belongs with position, which is currently specified in the shipstate, with an option to specify a default for a derivedObject in the derivedObject's referenceState.

Scale, on the other hand, can invariably be considered constant for a given derivedObject, so could be stored on the derivedObject directly. Scale will impact calculations of CG etc., so it can't meaningfully be added without thoughtful consideration.

I must admit that this all seems like a mess, though.

**Comment by EliasHasle** [comment]
#87 outlined a way to introduce scale and rotation for derived objects, at the same time moving position into a property. I am not convinced it is the right way, or a prioritized task.

**Comment by hmgaspar** [comment]
Ok, we close for now. If necessary, we open.

**Comment by EliasHasle** [comment]
As with the object picking, I include here the relevant source files for introducing this.

A version of the DBB CSV to JSON converter that sets position within an object:
https://github.com/EliasHasle/vesseljs/blob/rotation-scale/examples/Utilities/Block_CSV_to_JSON.html

A version of `DerivedObject.js` that _tries_ to handle position, scale, rotation:
https://github.com/EliasHasle/vesseljs/blob/2b12ed5a04d5b2703cb1dfc1735bfb6453e22e69/source/classes/DerivedObject.js

A different line 67 in `ShipState.js`:
https://github.com/EliasHasle/vesseljs/blob/2b12ed5a04d5b2703cb1dfc1735bfb6453e22e69/source/classes/ShipState.js#L67

Minor corresponding changes to `Ship3D_v2.js`:
https://github.com/EliasHasle/vesseljs/blob/2b12ed5a04d5b2703cb1dfc1735bfb6453e22e69/examples/js/Ship3D_v2.js
