### ISSUE TITLE
"Rugen-Kutta" should be "Runge-Kutta"...

### ISSUE THREAD

**Issue by EliasHasle** [shiplab/vesseljs#79]
https://github.com/shiplab/vesseljs/blob/fe2379a3ac9b6ff557ae291e15fb34a649f8cddd/examples/js/DynamicalMovement.js#L144

**Comment by icarofonseca** [comment]
@DiogoKramel please correct this

**Comment by EliasHasle** [comment]
By the way, "dimension" is with 's'.
